services:
  preflex-api:
    build:
      context: .
      args:
        GIT_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - .:/preflex-api:delegated
      - /preflex-api/vendor

  mariadb:
    image: mariadb:10.9
    ports: 
      - "3300:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
