services:
  preflex-api:
    build:
      context: .
    volumes:
      - .:/preflex-api
    ports:
      - "8080:8080"
  mariadb:
    image: mariadb:10.9
    ports: 
      - "3300:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
